% Create a rectangularArray with bowtieTriangular element.
% Generated by MATLAB(R) 9.12 and Antenna Toolbox 5.2.
% Generated on: 10-Sep-2022 13:37:36

% Create a bowtieTriangular antenna
% Generated by MATLAB(R) 9.12 and Antenna Toolbox 5.2.
% Generated on: 10-Sep-2022 13:26:28

%% Antenna Properties

function y = sample_simulation1(x1)
    antennaObject = design(bowtieTriangular, 2450*1e6);
    antennaObject.Length = 0.059325;
    % Show
    % figure;
    % show(antennaObject)

    %% Antenna Analysis
    % Define plot frequency
    plotFrequency = 2.45*1e9;
    % Define frequency range
    freqRange = (2205:24.5:2695)*1e6;
    % Reference Impedance
    refImpedance = 50;

    % pattern
    % figure;

    % pattern(antennaObject, plotFrequency)

    %% Array Properties

    SubObject =antennaObject;
    arrayObject = design(rectangularArray('Element', SubObject), 2450*1e6, SubObject);
    arrayObject.Size = [4 4];
    arrayObject.Element.Tilt = 90;
    arrayObject.Element.TiltAxis = [0, 1, 0];
    arrayObject.RowSpacing = 0.05;
    arrayObject.ColumnSpacing = 0.05;

    %% Array Analysis
    % Show for rectangularArray
    figure;
    show(arrayObject)
    % Layout for rectangularArray
    figure;
    layout(arrayObject)
    % Pattern for rectangularArray
    plotFrequency = 2.45*1e9; termination = 50;
    figure;
    pattern(arrayObject, plotFrequency, 'Termination', termination);
    y = 10;
end